### ISSUE TITLE
Need to translate from Russian to English

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/mod-buff-command#1]
Need to translate from Russian to English

**Comment by Winfidonarleyan** [comment]
https://github.com/Winfidonarleyan/BuffCommand-module/commit/ed10e3f6c7253df9010d02056f2dbb7a8cb0acfe

**Comment by BarbzYHOOL** [comment]
Thank you!! but you have rights on this repository too!  You can edit it directly, open Pull requests, merge PRs, create branches etc

Would you mind doing it there? (you can also just open a pull request from what you've just edited, it should take 30 sec))

**Comment by Winfidonarleyan** [comment]
I'm new to GitHub and do not know much, but I'll try: D
