### ISSUE TITLE
Command doesn't work

### ISSUE THREAD

**Issue by Knindzagxg** [azerothcore/mod-buff-command#16]
Compile and everything else is done without problems.
After enabling and sorting everything out:

```Loading player buff command ...
Loaded 9 buff in 1 ms```

But, when trying to use it, "module-buff-disabled"

Not really sure what making this problem, cause everything seems to be fine:

No errors during compile
Spells loaded
.buff command enabled on level 0

**Comment by wizzymore** [comment]
"But, when trying to use it, "module-buff-disabled" " - Can you please elaborate?
What exactly is the problem you are dealing with?
Also, please make sure that the spell id's are okay and in the config the module is enabled

**Comment by Knindzagxg** [comment]
Everything is enabled in config, spells are fine in database.
They load up as well when server start.

When using .buff command it just say that module is disabled but it's enabled and loaded.

**Comment by Knindzagxg** [comment]
Found whats the 'problem'.

It's nothing serious just a conflict between buff-module and kargatum-system
There is buff command in hes whole system as well, and if disabled there this one wont work as well.

**Comment by BarbzYHOOL** [comment]
yes kargatum-system is not "correct" for AC, you have to extract all modules one by one (if i recall) it's because Winfi doesn't use modules like us :(

**Comment by Knindzagxg** [comment]
It's working like a charm Barb, tested it fully.

Only problem is if you have hes system and buff-module so there conflict :P

**Comment by BarbzYHOOL** [comment]
might work but it's not correct/practical, it's a directory full of modules, and that's why you get a conflict, because it's an all in 1 solution

**Comment by Knindzagxg** [comment]
Yeah, but what i mean, you don't need other one since it's included in this one.

There are few extra modules so no need to download them as well.

**Comment by BarbzYHOOL** [comment]
yeah i checked kargatum system, in fact he made it work fine with AC, it's just not practical for us hence why I can't use it :'( 

anyway closing this
