### ISSUE TITLE
Compile Failed

### ISSUE THREAD

**Issue by littlehelper1987** [azerothcore/mod-buff-command#23]
Error: 
15>F:\Azerothcorenew\modules\mod-buff-command\src\BuffCommand.cpp(20,37): error C2039: "PQuery" ist kein Member von "DatabaseWorkerPool<WorldDatabaseConnection>".
15>F:\Azerothcorenew\src\server\database\Database\DatabaseEnv.h(35): message : Siehe Deklaration von "DatabaseWorkerPool<WorldDatabaseConnection>"
15>F:\Azerothcorenew\modules\mod-buff-command\src\BuffCommand.cpp(23,9): error C2039: "outErrorDb" ist kein Member von "Log".
15>F:\Azerothcorenew\src\common\Logging\Log.h(48): message : Siehe Deklaration von "Log"
15>F:\Azerothcorenew\modules\mod-buff-command\src\BuffCommand.cpp(24,9): error C2039: "outString" ist kein Member von "Log".
15>F:\Azerothcorenew\src\common\Logging\Log.h(48): message : Siehe Deklaration von "Log"
15>F:\Azerothcorenew\modules\mod-buff-command\src\BuffCommand.cpp(30,32): error C2039: "GetInt32" ist kein Member von "Field".
15>F:\Azerothcorenew\src\server\database\Database\Field.h(98): message : Siehe Deklaration von "Field"
15>F:\Azerothcorenew\modules\mod-buff-command\src\BuffCommand.cpp(35,8): error C2039: "outString" ist kein Member von "Log".
15>F:\Azerothcorenew\src\common\Logging\Log.h(48): message : Siehe Deklaration von "Log"
15>F:\Azerothcorenew\modules\mod-buff-command\src\BuffCommand.cpp(36,8): error C2039: "outString" ist kein Member von "Log".
15>F:\Azerothcorenew\src\common\Logging\Log.h(48): message : Siehe Deklaration von "Log"
15>F:\Azerothcorenew\modules\mod-buff-command\src\BuffCommand.cpp(81,10): error C2039: "outString" ist kein Member von "Log".
15>F:\Azerothcorenew\src\common\Logging\Log.h(48): message : Siehe Deklaration von "Log"
15>F:\Azerothcorenew\modules\mod-buff-command\src\BuffCommand.cpp(100,25): error C2039: "GetGameTime" ist kein Member von "IWorld".
15>F:\Azerothcorenew\src\server\game\World\IWorld.h(510): message : Siehe Deklaration von "IWorld"
15>F:\Azerothcorenew\modules\mod-buff-command\src\BuffCommand.cpp(100,141): error C2039: "GetGameTime" ist kein Member von "IWorld".
15>F:\Azerothcorenew\src\server\game\World\IWorld.h(510): message : Siehe Deklaration von "IWorld"
15>F:\Azerothcorenew\modules\mod-buff-command\src\BuffCommand.cpp(107,25): error C2039: "GetGameTime" ist kein Member von "IWorld".
15>F:\Azerothcorenew\src\server\game\World\IWorld.h(510): message : Siehe Deklaration von "IWorld"
15>F:\Azerothcorenew\modules\mod-buff-command\src\BuffCommand.cpp(108,56): error C2039: "GetGameTime" ist kein Member von "IWorld".
15>F:\Azerothcorenew\src\server\game\World\IWorld.h(510): message : Siehe Deklaration von "IWorld"
15>F:\Azerothcorenew\modules\mod-buff-command\src\BuffCommand.cpp(129,9): error C2039: "outString" ist kein Member von "Log".
15>F:\Azerothcorenew\src\common\Logging\Log.h(48): message : Siehe Deklaration von "Log"

**Comment by Helias** [comment]
fixed, test now
