### ISSUE TITLE
Command .buff non exist in the Core

### ISSUE THREAD

**Issue by littlehelper1987** [azerothcore/mod-buff-command#25]
After Fresh Compile, the .buff command dont exist in the core. 
Thank you for your Support :) 
![Unbenannt1](https://user-images.githubusercontent.com/76127576/208238620-b8d1698a-7252-4491-b047-93c63be24414.JPG)

**Comment by Helias** [comment]
it should be now `.mod_buff buff`, try it please

**Comment by littlehelper1987** [comment]
Thank you Helias, i tested it. Its now .mod_buff buff player 
Ty for ur Support.

**Comment by Helias** [comment]
I updated the documentation about it

**Comment by Fot3k** [comment]
Is there any way to change the command to be just .buff or something as simple?

Thanks.

**Comment by Helias** [comment]
there is, open an issue, when I'll have time I could do it

**Comment by Fot3k** [comment]
I managed to solve this myself by changing:

```
    ChatCommandTable GetCommands() const override
    {
        static ChatCommandTable moduleCommandTable =
        {
          { "buff",  HandleBuffCommand,  SEC_PLAYER, Console::No }
        };

        static ChatCommandTable commandTable =
        {
          { "mod_buff",  moduleCommandTable },
        };

        return commandTable;
    }
```

Replace with this:
```
    ChatCommandTable GetCommands() const override
{
    static ChatCommandTable commandTable =
    {
        { "buff",  HandleBuffCommand,  SEC_PLAYER, Console::No },
    };
    return commandTable;
}
```

**Comment by Helias** [comment]
create a PR for it please
