### ISSUE TITLE
getLevel is not a member of 'Player'

### ISSUE THREAD

**Issue by Doottacc** [azerothcore/mod-buff-command#28]
Currnetly having an issue generating my server with an error on line 73 for getLevel is not a member of Player.

![image](https://github.com/user-attachments/assets/0d65a92c-89f3-4e33-830b-3a5fcfb2d7ef)

**Comment by Helias** [comment]
issue fixed by https://github.com/azerothcore/mod-buff-command/commit/a22d153727277724799db42d4de28df7bb4a0d9f
